### ISSUE TITLE
recursion error upon reading .bib file

### ISSUE THREAD

**Issue by kirk86** [aclements/biblib#3]
Hi I just installed `biblib` and run the following simple example from the tutorials

```
import biblib
db  = biblib.FileBibDB('path/to/file.bib', mode='r')
for entry in db.values():
      print(entry)
```

I get the following error

```
Traceback (most recent call last):
  File "/python3.6/site-packages/biblib/_entry.py", line 48, in __new__
    return cls._registeredTypes[inputdict['ENTRYTYPE']](inputdict)
  File "/python3.6/site-packages/biblib/_entry.py", line 48, in __new__
    return cls._registeredTypes[inputdict['ENTRYTYPE']](inputdict)
  File "/python3.6/site-packages/biblib/_entry.py", line 48, in __new__
    return cls._registeredTypes[inputdict['ENTRYTYPE']](inputdict)
  [Previous line repeated 997 more times]
RecursionError: maximum recursion depth exceeded while calling a Python object
```

Even tried increasing the recursion stack but nothing
```
import sys
sys.setrecursionlimit(10000)
```
Any ideas?

**Comment by hendriks73** [comment]
You seem to be using http://wgserve.de/biblib/ and not this package. Unfortunately, they have the same name.

**Comment by thomasmansencal** [comment]
Interesting I got the same issue, and realised that the package I was using was not the one I intended!

**Comment by peterschindler** [comment]
Same here...could anyone solve the issue? Or is the package just not working?

**Comment by thomasmansencal** [comment]
@peterschindler : The Pypi package is simply not the same than this repository. For what it is worth, I forked this repo and made a Pypi package: https://pypi.org/project/biblib-simple/

**Comment by peterschindler** [comment]
@KelSolaar Yes, I am aware but I wasn't able to find a github of the Pypi package - so, not sure how to report a bug for the other package. Anyway, thanks for the fork. Actually, for my purposes, I will just use pybtex for now.
